/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * TestScribble.java
 *
 * Created on Nov 23, 2011, 7:43:58 PM
 */
package com.hrauf.util.test;

import java.util.logging.Level;
import java.util.logging.Logger;
import org.jdesktop.application.Action;

/**
 *
 * @author Hammad
 */
public class TestScribble extends javax.swing.JDialog {

    /** Creates new form TestScribble */
    public TestScribble(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        scribblePanel1.setSize(20, 20);
        scribblePanel2.setSize(20, 20);
        invalidate();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        scribblePanel1 = new com.hrauf.util.ScribblePanel();
        scribblePanel2 = new com.hrauf.util.ScribblePanel();
        butPutImage = new javax.swing.JButton();
        butCopyImage = new javax.swing.JButton();
        scribblePanel3 = new com.hrauf.util.ScribblePanel();
        scribblePanel4 = new com.hrauf.util.ScribblePanel();

        jButton1.setText("jButton1");
        jButton1.setName("jButton1"); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TestScribble");

        scribblePanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        scribblePanel1.setName("scribblePanel1"); // NOI18N
        scribblePanel1.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout scribblePanel1Layout = new javax.swing.GroupLayout(scribblePanel1);
        scribblePanel1.setLayout(scribblePanel1Layout);
        scribblePanel1Layout.setHorizontalGroup(
            scribblePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        scribblePanel1Layout.setVerticalGroup(
            scribblePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        scribblePanel2.setName("scribblePanel2"); // NOI18N
        scribblePanel2.setPreferredSize(new java.awt.Dimension(20, 20));

        javax.swing.GroupLayout scribblePanel2Layout = new javax.swing.GroupLayout(scribblePanel2);
        scribblePanel2.setLayout(scribblePanel2Layout);
        scribblePanel2Layout.setHorizontalGroup(
            scribblePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 24, Short.MAX_VALUE)
        );
        scribblePanel2Layout.setVerticalGroup(
            scribblePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance().getContext().getActionMap(TestScribble.class, this);
        butPutImage.setAction(actionMap.get("butPutImage_Action")); // NOI18N
        butPutImage.setName("butPutImage"); // NOI18N

        butCopyImage.setAction(actionMap.get("copyImage_Action")); // NOI18N
        butCopyImage.setName("butCopyImage"); // NOI18N

        scribblePanel3.setName("scribblePanel3"); // NOI18N

        javax.swing.GroupLayout scribblePanel3Layout = new javax.swing.GroupLayout(scribblePanel3);
        scribblePanel3.setLayout(scribblePanel3Layout);
        scribblePanel3Layout.setHorizontalGroup(
            scribblePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        scribblePanel3Layout.setVerticalGroup(
            scribblePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        scribblePanel4.setName("scribblePanel4"); // NOI18N

        javax.swing.GroupLayout scribblePanel4Layout = new javax.swing.GroupLayout(scribblePanel4);
        scribblePanel4.setLayout(scribblePanel4Layout);
        scribblePanel4Layout.setHorizontalGroup(
            scribblePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        scribblePanel4Layout.setVerticalGroup(
            scribblePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(butCopyImage)
                    .addComponent(butPutImage))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(scribblePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(scribblePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addContainerGap(247, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(196, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scribblePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scribblePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(104, 104, 104))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(scribblePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scribblePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(butCopyImage)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butPutImage)))
                .addGap(37, 37, 37)
                .addComponent(scribblePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(scribblePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestScribble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestScribble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestScribble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestScribble.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                TestScribble dialog = new TestScribble(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    @Action
    public void butPutImage_Action() {
        int width = 24;
        int height = 20;
        int prod = width*height;
        byte b2[] = new byte[prod];
        for (int i = 0; i < height; i++) {
            for (int j = 0; j < width; j++) {
                if (((i >= 3)&(i<=5))|((j >= 3)&(j<=5))) {
                    b2[(i * (width)) + j] = (byte) 0x00;
                } else {
                    b2[(i * (width)) + j] = (byte) 0xff;
                }
            }
        }
        try {
            scribblePanel1.setByteArray(width, height, b2);
        } catch (Exception ex) {
            Logger.getLogger(TestScribble.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    @Action
    public void copyImage_Action() {
        scribblePanel1.mergeLayers();
        byte[] b1 = scribblePanel1.getByteArray();

        scribblePanel3.mergeLayers();
        byte[] b2 = scribblePanel3.getByteArray();
        
        try {
            scribblePanel2.setByteArray(b1);
            scribblePanel4.setByteArray(b2);
        } catch (Exception ex) {
            Logger.getLogger(TestScribble.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton butCopyImage;
    private javax.swing.JButton butPutImage;
    private javax.swing.JButton jButton1;
    private com.hrauf.util.ScribblePanel scribblePanel1;
    private com.hrauf.util.ScribblePanel scribblePanel2;
    private com.hrauf.util.ScribblePanel scribblePanel3;
    private com.hrauf.util.ScribblePanel scribblePanel4;
    // End of variables declaration//GEN-END:variables
}
