/*
 * EditableInchBox.java
 *
 * Created on June 28, 2008, 2:41 PM
 */
package com.hrauf.util;

import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Hammad
 */
public class EditableInchBox extends javax.swing.JPanel {

    protected double decimalDouble;
    public static final String PROP_DECIMALDOUBLE = "decimalDouble";

    /**
     * Get the value of decimalDouble
     *
     * @return the value of decimalDouble
     */
    public double getDecimalDouble() {
        decimalDouble = this.fractionalValue.getDecimalDouble();
        return decimalDouble;
    }

    /**
     * Set the value of decimalDouble
     *
     * @param decimalDouble new value of decimalDouble
     */
    public void setDecimalDouble(double decimalDouble) {
        double oldDecimalDouble = this.decimalDouble;
        this.decimalDouble = decimalDouble;
        try {
            this.fractionalValue.setDecimalDouble(decimalDouble);
        } catch (Exception ex) {
            Logger.getLogger(EditableInchBox.class.getName()).log(Level.SEVERE, "Exception: Setting value in Inch Box.", ex);
            com.hrauf.util.ErrorDialog.showErrorRecomendation("Exception: Setting value in Inch Box.", "Check for error in Fraction Format String.");
        }
        propertyChangeSupport.firePropertyChange(PROP_DECIMALDOUBLE, oldDecimalDouble, decimalDouble);
    }


    protected String fractionStr;
    public static final String PROP_FRACTIONSTR = "fractionStr";

    @Override
    public void setEnabled(boolean enabled) {
        super.setEnabled(enabled);
        fractionalValue.setEnabled(enabled);
    }



    /**
     * Get the value of fractionStr
     *
     * @return the value of fractionStr
     */
    public String getFractionStr() {
        fractionStr = this.fractionalValue.getFractionString();
        return fractionStr;
    }

    /**
     * Set the value of fractionStr
     *
     * @param fractionStr new value of fractionStr
     */
    public void setFractionStr(String fractionStr) throws Exception {
        String oldFractionStr = this.fractionStr;
        this.fractionStr = fractionStr;
        this.fractionalValue.setFractionString(this.fractionStr);
        propertyChangeSupport.firePropertyChange(PROP_FRACTIONSTR, oldFractionStr, fractionStr);
    }
    private PropertyChangeSupport propertyChangeSupport = new PropertyChangeSupport(this);

    /**
     * Add PropertyChangeListener.
     *
     * @param listener
     */
    public void addPropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.addPropertyChangeListener(listener);
    }

    /**
     * Remove PropertyChangeListener.
     *
     * @param listener
     */
    public void removePropertyChangeListener(PropertyChangeListener listener) {
        propertyChangeSupport.removePropertyChangeListener(listener);
    }

    private float floatValue = 0;

    /** Creates new form EditableInchBox */
    public EditableInchBox() {
        initComponents();
    }

    /** Creates new form EditableInchBox */
    public EditableInchBox(String fracString) throws Exception {
        initComponents();
        this.fractionalValue.setFractionString(fracString);
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpanelValue = new javax.swing.JPanel();
        fractionalValue = new com.hrauf.util.FractionalJTextField();
        jspaneBoxTitle = new javax.swing.JScrollPane();
        jtxtInchBoxTitle = new javax.swing.JTextArea();

       org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(EditableInchBox.class);
       setBackground(resourceMap.getColor("Form.background")); // NOI18N
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setMinimumSize(new java.awt.Dimension(90, 40));
        setName("Form"); // NOI18N
        setPreferredSize(new java.awt.Dimension(80, 68));
        setLayout(new java.awt.BorderLayout());

        jpanelValue.setName("jpanelValue"); // NOI18N
        jpanelValue.setLayout(new javax.swing.BoxLayout(jpanelValue, javax.swing.BoxLayout.LINE_AXIS));

        try {
          fractionalValue.setFractionString(resourceMap.getString("fractionalValue.fractionString")); // NOI18N
        } catch (java.lang.Exception e1) {
            e1.printStackTrace();
        }
        fractionalValue.setName("fractionalValue"); // NOI18N
        jpanelValue.add(fractionalValue);

        add(jpanelValue, java.awt.BorderLayout.CENTER);

        jspaneBoxTitle.setName("jspaneBoxTitle"); // NOI18N

        jtxtInchBoxTitle.setColumns(20);
        jtxtInchBoxTitle.setEditable(false);
        jtxtInchBoxTitle.setFont(resourceMap.getFont("jtxtInchBoxTitle.font")); // NOI18N
        jtxtInchBoxTitle.setLineWrap(true);
        jtxtInchBoxTitle.setRows(2);
        jtxtInchBoxTitle.setWrapStyleWord(true);
        jtxtInchBoxTitle.setAutoscrolls(false);
        jtxtInchBoxTitle.setDisabledTextColor(resourceMap.getColor("jtxtInchBoxTitle.disabledTextColor")); // NOI18N
        jtxtInchBoxTitle.setEnabled(false);
        jtxtInchBoxTitle.setFocusable(false);
        jtxtInchBoxTitle.setName("jtxtInchBoxTitle"); // NOI18N
        jtxtInchBoxTitle.setPreferredSize(new java.awt.Dimension(64, 24));
        jspaneBoxTitle.setViewportView(jtxtInchBoxTitle);

        add(jspaneBoxTitle, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.hrauf.util.FractionalJTextField fractionalValue;
    protected javax.swing.JPanel jpanelValue;
    protected javax.swing.JScrollPane jspaneBoxTitle;
    protected javax.swing.JTextArea jtxtInchBoxTitle;
    // End of variables declaration//GEN-END:variables
    public String getInchBoxLabel() {
        return jtxtInchBoxTitle.getText();
    }

    public void setInchBoxLabel(String inchBoxLabel) {
        this.jtxtInchBoxTitle.setText(inchBoxLabel);
    }

//End of class
}
