/*
 * ErrorDialog.java
 *
 * Created on August 18, 2008, 5:14 PM
 */

package com.hrauf.util;

import javax.swing.JScrollBar;

/**
 *
 * @author  Hammad
 */
public class MessageDialog extends javax.swing.JDialog {
    private JScrollBar hscrollbar;
    private JScrollBar vscrollbar;

    /** Creates new form ErrorDialog */
    public MessageDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        double h = java.awt.Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        double w = java.awt.Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        int x = (int) ((w - this.getWidth()) / 2);
        int y = (int) ((h - this.getHeight()) / 2);
        this.setLocation(x, y);
    }


        /** Creates new form ErrorDialog */
    public MessageDialog(java.awt.Dialog parent, boolean modal) {
       // super(parent, modal);
        super(parent, modal);
        initComponents();
        double h = java.awt.Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        double w = java.awt.Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        int x = (int) ((w - this.getWidth()) / 2);
        int y = (int) ((h - this.getHeight()) / 2);
        this.setLocation(x, y);
    }

            /** Creates new form ErrorDialog */
    public MessageDialog() {
        super();
        initComponents();
        double h = java.awt.Toolkit.getDefaultToolkit().getScreenSize().getHeight();
        double w = java.awt.Toolkit.getDefaultToolkit().getScreenSize().getWidth();
        int x = (int) ((w - this.getWidth()) / 2);
        int y = (int) ((h - this.getHeight()) / 2);
        this.setLocation(x, y);
    }


    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jpanelButtons = new javax.swing.JPanel();
        jbutOK = new javax.swing.JButton();
        jscrollMessage = new javax.swing.JScrollPane();
        jtxtMessage = new javax.swing.JTextPane();
        jscrollRecomendation = new javax.swing.JScrollPane();
        jtxtRecommendation = new javax.swing.JTextPane();

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance().getContext().getResourceMap(MessageDialog.class);
        setTitle(resourceMap.getString("Form.title")); // NOI18N
        setName("Form"); // NOI18N
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jpanelButtons.setName("jpanelButtons"); // NOI18N

        jbutOK.setText(resourceMap.getString("jbutOK.text")); // NOI18N
        jbutOK.setName("jbutOK"); // NOI18N
        jbutOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbutOKPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelButtonsLayout = new javax.swing.GroupLayout(jpanelButtons);
        jpanelButtons.setLayout(jpanelButtonsLayout);
        jpanelButtonsLayout.setHorizontalGroup(
            jpanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbutOK)
                .addContainerGap())
        );
        jpanelButtonsLayout.setVerticalGroup(
            jpanelButtonsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelButtonsLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbutOK))
        );

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        getContentPane().add(jpanelButtons, gridBagConstraints);

        jscrollMessage.setName("jscrollMessage"); // NOI18N
        jscrollMessage.setPreferredSize(new java.awt.Dimension(300, 115));

        jtxtMessage.setBackground(resourceMap.getColor("jtxtMessage.background")); // NOI18N
        jtxtMessage.setEditable(false);
        jtxtMessage.setFocusable(false);
        jtxtMessage.setName("jtxtMessage"); // NOI18N
        jtxtMessage.setRequestFocusEnabled(false);
        jscrollMessage.setViewportView(jtxtMessage);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.gridheight = 3;
        getContentPane().add(jscrollMessage, gridBagConstraints);

        jscrollRecomendation.setBorder(null);
        jscrollRecomendation.setAutoscrolls(true);
        jscrollRecomendation.setName("jscrollRecomendation"); // NOI18N
        jscrollRecomendation.setPreferredSize(new java.awt.Dimension(300, 60));

        jtxtRecommendation.setBackground(resourceMap.getColor("jtxtRecommendation.background")); // NOI18N
        jtxtRecommendation.setBorder(null);
        jtxtRecommendation.setEditable(false);
        jtxtRecommendation.setFocusable(false);
        jtxtRecommendation.setName("jtxtRecommendation"); // NOI18N
        jscrollRecomendation.setViewportView(jtxtRecommendation);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 6;
        getContentPane().add(jscrollRecomendation, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jbutOKPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbutOKPerformed
        this.dispose();
}//GEN-LAST:event_jbutOKPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MessageDialog dialog = new MessageDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jbutOK;
    private javax.swing.JPanel jpanelButtons;
    private javax.swing.JScrollPane jscrollMessage;
    private javax.swing.JScrollPane jscrollRecomendation;
    private javax.swing.JTextPane jtxtMessage;
    private javax.swing.JTextPane jtxtRecommendation;
    // End of variables declaration//GEN-END:variables

public void setRecommendation(String recomendation) {
    jtxtRecommendation.setText(recomendation);
    jtxtRecommendation.revalidate();
    this.getContentPane().repaint();
}

public String getRecommendation() {
    return jtxtRecommendation.getText();
}

public void clearRecommendation() {
    jtxtRecommendation.setText("");
    jtxtRecommendation.revalidate();
    this.getContentPane().repaint();
}

public void setMessage(String message) {
    jtxtMessage.setText(message);
    jtxtMessage.revalidate();
    jscrollMessage.repaint();
}

public String getMessage() {
    return jtxtMessage.getText();
}

public void clearMessage() {
    jtxtMessage.setText("");
    jtxtMessage.revalidate();
    jscrollMessage.repaint();
}

public static void showMessageRecomendation(java.awt.Frame Parent, String msg, String recommendation) {
     MessageDialog ewin = new MessageDialog(Parent, true);
     ewin.setMessage(msg);
     ewin.setRecommendation("Recommended Action:\n" + recommendation);
     ewin.setVisible(true);
}


public static void showMessage(java.awt.Frame Parent, String msg) {
     MessageDialog ewin = new MessageDialog(Parent, true);
     ewin.setMessage(msg);
     ewin.setRecommendation("");
     ewin.setVisible(true);
}

public static void showTitleMsg(java.awt.Frame Parent, String title, String msg) {
     ErrorDialog ewin = new ErrorDialog(Parent, true);
     ewin.setTitle(title);
     ewin.setMessage(msg);
     ewin.setRecommendation("");
     ewin.setVisible(true);
}

public static void showTitleMsgRecomendation(java.awt.Frame Parent, String title, String msg, String recomendation) {
     ErrorDialog ewin = new ErrorDialog(Parent, true);
     ewin.setTitle(title);
     ewin.setMessage(msg);
     ewin.setRecommendation(recomendation);
     ewin.setVisible(true);
}

public static void showMessageRecomendation(java.awt.Dialog Parent, String msg, String recommendation) {
     MessageDialog ewin = new MessageDialog(Parent, true);
     ewin.setMessage(msg);
     ewin.setRecommendation("Recommended Action:\n" + recommendation);
     ewin.setVisible(true);
}


public static void showMessage(java.awt.Dialog Parent, String msg) {
     MessageDialog ewin = new MessageDialog(Parent, true);
     ewin.setMessage(msg);
     ewin.setRecommendation("");
     ewin.setVisible(true);
}

public static void showTitleMsg(java.awt.Dialog Parent, String title, String msg) {
     ErrorDialog ewin = new ErrorDialog(Parent, true);
     ewin.setTitle(title);
     ewin.setMessage(msg);
     ewin.setRecommendation("");
     ewin.setVisible(true);
}

public static void showTitleMsgRecomendation(java.awt.Dialog Parent, String title, String msg, String recomendation) {
     ErrorDialog ewin = new ErrorDialog(Parent, true);
     ewin.setTitle(title);
     ewin.setMessage(msg);
     ewin.setRecommendation(recomendation);
     ewin.setVisible(true);
}


public static void showMessageRecomendation(String msg, String recommendation) {
     MessageDialog ewin = new MessageDialog();
     ewin.setMessage(msg);
     ewin.setRecommendation("Recommended Action:\n" + recommendation);
     ewin.setVisible(true);
}


public static void showMessage(String msg) {
     MessageDialog ewin = new MessageDialog();
     ewin.setMessage(msg);
     ewin.setRecommendation("");
     ewin.setVisible(true);
}

public static void showTitleMsg(String title, String msg) {
     ErrorDialog ewin = new ErrorDialog();
     ewin.setTitle(title);
     ewin.setMessage(msg);
     ewin.setRecommendation("");
     ewin.setVisible(true);
}

public static void showTitleMsgRecomendation(String title, String msg, String recomendation) {
     ErrorDialog ewin = new ErrorDialog();
     ewin.setTitle(title);
     ewin.setMessage(msg);
     ewin.setRecommendation(recomendation);
     ewin.setVisible(true);
}

}
